spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nic
    username: root
    password: akindu123
  jpa:
    hibernate:
      ddl-auto: create


  mail:
    host: smtp.gmail.com
    port: 587
    username: akiyaramsith2002@gmail.com
    password: //your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
